# Generated by Django 4.2 on 2025-11-02 20:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MAC_OFFICER', 'MAC PR Officer'), ('MICAT_REVIEWER', 'MICAT Reviewer/Editor'), ('ADMIN', 'System Administrator')], default='MAC_OFFICER', help_text="User's role in the system", max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_active', models.BooleanField(default=True, help_text='Can this user log in?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the Ministry/Agency/Commission', max_length=200, unique=True)),
                ('acronym', models.CharField(help_text='Short name (e.g., MICAT, MOH, MOE)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this MAC does')),
                ('email', models.EmailField(blank=True, help_text='Official contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mac_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this MAC currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MAC',
                'verbose_name_plural': 'MACs',
                'ordering': ['acronym'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content', max_length=300)),
                ('content_type', models.CharField(choices=[('PRESS_RELEASE', 'Press Release'), ('ANNOUNCEMENT', 'Announcement'), ('SPEECH', 'Speech'), ('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='PRESS_RELEASE', max_length=20)),
                ('description', models.TextField(help_text='Summary or description of the content')),
                ('tags', models.CharField(blank=True, help_text='Keywords separated by commas (e.g., health, covid, vaccine)', max_length=500)),
                ('file', models.FileField(help_text='Upload the content file', upload_to='submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'xlsx', 'xls'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('RETURNED', 'Returned for Edits')], default='PENDING', max_length=20)),
                ('is_confidential', models.BooleanField(default=False, help_text='Is this content confidential?')),
                ('is_published', models.BooleanField(default=False, help_text='Is this visible in the public library?')),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True, help_text='Comments from MICAT reviewer')),
                ('denial_reason', models.TextField(blank=True, help_text='Reason if denied')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac', models.ForeignKey(help_text='Which MAC submitted this', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.mac')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='MICAT reviewer assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Which officer submitted this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes (not visible to MAC officer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMISSION_CREATED', 'Submission Created'), ('SUBMISSION_UPDATED', 'Submission Updated'), ('SUBMISSION_REVIEWED', 'Submission Reviewed'), ('SUBMISSION_APPROVED', 'Submission Approved'), ('SUBMISSION_DENIED', 'Submission Denied'), ('SUBMISSION_RETURNED', 'Submission Returned for Edits'), ('SUBMISSION_PUBLISHED', 'Submission Published'), ('COMMENT_ADDED', 'Comment Added'), ('USER_LOGIN', 'User Logged In'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('MAC_CREATED', 'MAC Created'), ('MAC_UPDATED', 'MAC Updated')], max_length=50)),
                ('description', models.TextField(help_text='Details of what happened')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.submission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='mac',
            field=models.ForeignKey(blank=True, help_text='Which MAC this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.mac'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-submitted_at'], name='core_submis_status_233851_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['mac', 'status'], name='core_submis_mac_id_bcf8a2_idx'),
        ),
    ]
